In [1]:
# date: 2018/07/03
# Construct a MLN network to solve the mnist handwriting problem
# Main layers included in the MLN network: 
# Hidden layer 
# Output layer
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
np.random.seed(10)

C:\Users\nctu\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
from keras.datasets import mnist

In [3]:
(x_train_image, y_train_label), \
(x_test_image, y_test_label) = mnist.load_data()

In [4]:
print('train data=', x_train_image.shape)
print('test data=', y_train_label.shape)

train data= (60000, 28, 28)
test data= (60000,)


In [5]:
import matplotlib.pyplot as plt
def plot_image(image):
    fig = plt.gcf()
    fig.set_size_inches(2,2)
    plt.imshow(image, cmap = 'binary')
    plt.show()

In [6]:
x_train = x_train_image.reshape(60000, 784).astype('float32')
x_test = x_test_image.reshape(10000, 784).astype('float32')

In [7]:
print('x_train_image', x_train.shape)
print('x_test_image', x_train.shape)

x_train_image (60000, 784)
x_test_image (60000, 784)


In [8]:
x_train[0]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [9]:
x_train_normalize = x_train/255
x_test_normalize = x_test/255

In [10]:
x_train_normalize[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [11]:
y_train_label[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [12]:
y_trainonehot = np_utils.to_categorical(y_train_label)
y_testonehot = np_utils.to_categorical(y_test_label)

In [13]:
y_trainonehot[:5]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [14]:
model = Sequential()

In [15]:
#Construct hidden layer
model.add(Dense(units = 256,
                input_dim = 784,
                kernel_initializer = 'normal',
                activation = 'relu'
))

In [16]:
#Construct output layer
model.add(Dense(units = 10,
                kernel_initializer = 'normal',
                activation = 'softmax'
))

In [17]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               200960    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                2570      
Total params: 203,530
Trainable params: 203,530
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
model.compile(loss = 'categorical_crossentropy',
              optimizer = 'adam', metrics = ['accuracy']
)

In [19]:
train_history = model.fit(x = x_train_normalize,
                          y = y_trainonehot, validation_split = 0.2,
                          epochs = 10, batch_size = 200, verbose = 2
                         )

Train on 48000 samples, validate on 12000 samples
Epoch 1/10
 - 1s - loss: 0.4396 - acc: 0.8825 - val_loss: 0.2180 - val_acc: 0.9408
Epoch 2/10
 - 1s - loss: 0.1909 - acc: 0.9456 - val_loss: 0.1556 - val_acc: 0.9559
Epoch 3/10
 - 1s - loss: 0.1357 - acc: 0.9619 - val_loss: 0.1260 - val_acc: 0.9649
Epoch 4/10
 - 1s - loss: 0.1032 - acc: 0.9700 - val_loss: 0.1128 - val_acc: 0.9680
Epoch 5/10
 - 1s - loss: 0.0816 - acc: 0.9774 - val_loss: 0.0981 - val_acc: 0.9717
Epoch 6/10
 - 1s - loss: 0.0664 - acc: 0.9815 - val_loss: 0.0933 - val_acc: 0.9718
Epoch 7/10
 - 1s - loss: 0.0549 - acc: 0.9850 - val_loss: 0.0914 - val_acc: 0.9729
Epoch 8/10
 - 1s - loss: 0.0462 - acc: 0.9874 - val_loss: 0.0828 - val_acc: 0.9759
Epoch 9/10
 - 1s - loss: 0.0382 - acc: 0.9902 - val_loss: 0.0821 - val_acc: 0.9763
Epoch 10/10
 - 1s - loss: 0.0319 - acc: 0.9915 - val_loss: 0.0797 - val_acc: 0.9771
